[package]
name = "wavedash"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
  ".",
  "crates/host",
  "crates/macros",
  "example",
  "example/crates/host",
]

[dependencies]
wavedash-macros = { path = "crates/macros" }
