[package]
name = "wavedash-example-host"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.3"
wavedash-host = { path = "../../../crates/host" }
wavedash-example-core = { path = "../core" }
